meta:
    site_title: "0xDECAFBAD"
    site_subtitle: "It's all spinning wheels and self-doubt until the first pot of coffee."
    site_language: "en"
    absolute_baseurl: http://decafbad.com/blog
    domain: decafbad.com
    author:
        full_name: Leslie Michael Orchard
        short_name: lmorchard
        name: l.m.orchard
        email: l.m.orchard@pobox.com

tag_dir: tag
baseurl: /
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title

debug: false

